name: buildAndDeploy
on:
  push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2.3.1

    - name: buildAndDeploy
      env:
        VUE_APP_CLIENT_ID: ${{ secrets.VUE_APP_CLIENT_ID }}
        VUE_APP_YOUTUBE_API: ${{ secrets.VUE_APP_YOUTUBE_API }}
      run: |
        yarn install
        yarn build
        
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
